#!/bin/bash

echo "Adding missing translation keys..."

# Add missing translation keys (561-568)
sudo -u postgres psql -d vault -c "
INSERT INTO feature.translation_key (id, name, is_tw_native, \"group\", note) VALUES
(561, 'UPLOAD_ENABLED_CLICK_TO_DISABLE', false, 'General', 'Upload enabled (click to disable)'),
(562, 'UPLOAD_DISABLED_CLICK_TO_ENABLE', false, 'General', 'Upload disabled (click to enable)'),
(563, 'SURE_DISABLE_UPLOADS', false, 'General', 'Are you sure you want to disable uploads?'),
(564, 'ENABLE_UPLOAD', false, 'General', 'Enable upload'),
(565, 'READ_AND_ACCEPT_TERMS', false, 'General', 'Have you read and accepted the terms?'),
(566, 'UPLOAD_NOT_ENABLED_ENABLE_FIRST', false, 'General', 'Upload is currently not enabled! First enable it.'),
(567, 'I_ACCEPT', false, 'General', 'I accept'),
(568, 'VAULT_PRIVACY_DISCLAIMER', false, 'General', 'Vault privacy disclaimer')
ON CONFLICT (id) DO NOTHING;
"

echo "Importing all Hungarian translations..."

# Import ALL Hungarian translations with proper escaping
sudo -u postgres psql -d vault -c "
INSERT INTO feature.translation (translation_id, key, value) VALUES
(2, 2, 'Nyisd meg a Vault-ot'),
(2, 3, 'Érkezési idő'),
(2, 4, 'Időpont'),
(2, 5, 'Ez a szkript csak prémium fiókkal használható!'),
(2, 6, 'Ez az első alkalom, hogy futtatod a szkriptet – kérlek, olvasd el az alábbi ADATGYŰJTÉSI feltételeket. Ez a szkript a Vault interfészeként szolgál, amely egy privát eszköz a Klánháború adatainak gyűjtésére. Minden adat a saját lokális tárolódban kerül mentésre, és teljes mértékben te döntöd el, hogy megosztod-e a szerverrel vagy sem. A naplózott információk kizárólag az alábbiakra korlátozódnak: - Hitelesítési token - Játékos ID - Klán ID - Lekért végpont - Tranzakció időpontja A szkript által gyűjtött információk soha nem kerülnek megosztásra harmadik felekkel vagy illetéktelen klánokkal/játékosokkal. A feltételeket később is megtekintheted a szkript futtatása után. Ha nem fogadod el azokat, egyszerűen ne futtasd a szkriptet újra. Elfogadod ezeket a feltételeket?'),
(2, 7, 'Köszönjük, kérjük, futtassa újra a szkriptet a használat megkezdéséhez.'),
(2, 8, 'A scipt nem lesz futtatva!'),
(2, 9, 'A Vault nemrég frissült, néhány adatot újra kell töltenie.'),
(2, 10, 'BB-kód készítése visszaidőzítéshez'),
(2, 11, 'Régóta nem töltött fel adatot, nem használhatja a visszaidőzítő szkriptet, amíg ezt meg nem teszi. Töltse fel adatait, majd frissítse az oldalt, és futtassa újra ezt a szkriptet.'),
(2, 12, 'Parancsok'),
(2, 13, 'Bejövő támadások'),
(2, 14, 'Jelentések'),
(2, 15, 'Egységek'),
(2, 16, 'Fel kell töltened:'),
(2, 17, 'Hiba keletkezett..'),
(2, 18, 'Nincsenek elérhető parancsok'),
(2, 19, 'Nincs elérhető adat'),
(2, 20, 'Csapatok'),
(2, 21, 'Faluból küldve'),
(2, 22, 'Időpont'),
(2, 23, 'Időpont'),
(2, 24, 'Szükséges csapatok'),
(2, 25, 'Vault'),
(2, 26, 'Ez a Vault. Győződj meg róla, hogy feltöltöd a jelentéseidet stb. a Feltöltés fülön. Futtasd ezt a szkriptet a Térképen vagy a Bejövő támadások oldalon, hogy láthass mindent, amit a Vault kínál.'),
(2, 27, 'Kész'),
(2, 28, 'A jelenlegi feltöltések a felugró ablak bezárása után is folytatódnak.'),
(2, 29, '{numIncs} bejövő támadás még nem lett feltöltve a Vaultba, ezért nem kap címkét!'),
(2, 30, 'Már régóta nem töltöttél fel adatot, ezért a címkézés addig nem használható, amíg nem töltesz fel újat.'),
(2, 31, 'Megjegyzés – ez a funkció KÍSÉRLETI jellegű, ezért előfordulhat, hogy nem pontos!'),
(2, 32, 'Látható bejövő támadások feltöltése'),
(2, 33, 'Kód'),
(2, 34, 'Részletek'),
(2, 35, 'Legvalószínűbb egységtípus (a címkéd alapján vagy automatikusan számítva)'),
(2, 36, 'Egy közülük: Fake, Nuke'),
(2, 37, '% A faluban ismert teljes nuke százaléka, pl. 89% vagy ?%'),
(2, 38, 'A faluban ismert támadó népesség, pl. 19.2k vagy ?k'),
(2, 39, '% A parancs elküldésekor a faluba visszatérő ismert teljes nuke százaléka, pl. 89% vagy ?%'),
(2, 40, 'A parancs elküldésekor a faluba visszatérő ismert támadó népesség, pl. 19.2k vagy ?k'),
(2, 41, '# a faluban ismert katapultok száma'),
(2, 42, '# Összes parancs száma a faluból'),
(2, 43, 'Támadó játékos neve'),
(2, 44, 'Támadó játékos falva'),
(2, 45, 'Védekező neve'),
(2, 46, 'Védekező játékos falva'),
(2, 47, 'Származási hely koordinátái'),
(2, 48, 'Célállomás'),
(2, 49, 'A falu típusa: támadó, védekező vagy ismeretlen'),
(2, 50, 'Az általad hozzáadott egyéni címkék a parancshoz, amelyeket érintetlenül kell hagyni; ezek idézőjelek között jelennek meg, például „Kitért".'),
(2, 51, 'Tag format:'),
(2, 52, 'Reset'),
(2, 53, 'Csak a címkézetlen bejövőket jelöld meg'),
(2, 54, 'Címkézés „Fake"-ként, ha kevesebb mint'),
(2, 55, 'ezer támadó népesség'),
(2, 56, 'Adatok nélküli bejövők támadások figyelmen kívül hagyása'),
(2, 57, 'Cimkézd összeset'),
(2, 58, 'Kiválasztott cimkézése'),
(2, 59, 'Visszaállítás a korábbi címkékre'),
(2, 60, 'Mégse'),
(2, 61, 'A címkézés eltarthat egy ideig!'),
(2, 62, 'Nem szám!'),
(2, 63, 'FIGYELMEZTETÉS – A fake-ek felismerése nem 100%-osan pontos, de bekapcsoltad a „címkézés fake-ként" opciót!'),
(2, 64, 'Nem választottál ki bejövő támadást!'),
(2, 65, 'Nincsenek bejövők, vagy minden címke naprakész.'),
(2, 66, 'Cimkézés megszakítva'),
(2, 67, '{numDone}/{numTotal} cimkézve ' || chr(40) || '{numFailed} nem skerült' || chr(41)),
(2, 68, 'Cimkézés:'),
(2, 69, 'Befejezve:'),
(2, 70, 'Megszakítva:'),
(2, 71, 'Ismeretlen'),
(2, 72, 'Fakes'),
(2, 73, 'Fake'),
(2, 74, 'Nuke?'),
(2, 75, 'Vault használva'),
(2, 76, 'Bármelyik'),
(2, 77, 'Nem'),
(2, 78, 'Már régóta nem töltöttél fel adatot, ezért a térképes scriptet nem tudod használni, amíg ezt meg nem teszed. Kattints fent az oldal tetején található „Megjelenítés" hivatkozásra a feltöltés megkezdéséhez. (Ezután frissítsd az oldalt.)'),
(2, 79, '# Fakes'),
(2, 80, '# Nukes'),
(2, 81, '# Foglalások'),
(2, 82, '# Védőcsapatok'),
(2, 83, '# Játékosok'),
(2, 84, 'Faluban'),
(2, 85, 'Erősítésben'),
(2, 86, 'Úton'),
(2, 87, 'Saját'),
(2, 88, 'Képezhető'),
(2, 89, 'Körülbelül ~{nukesRequired} nuke szükséges a falu kiürítéséhez {morale}% morálnál (az utolsó nuke vesztesége ~{lossPercent}%)'),
(2, 90, 'Megnézve'),
(2, 91, 'Friss szintadatok'),
(2, 92, 'Valószínűsíthető szintek'),
(2, 93, 'Hűség'),
(2, 94, 'Utolsó hűség'),
(2, 95, 'Valószínűsíthető hűség'),
(2, 96, 'Lebegő ablak beállításai'),
(2, 97, 'Parancsok'),
(2, 98, 'Képezhető'),
(2, 99, 'Épületek'),
(2, 100, 'Hűség'),
(2, 101, 'Átfedés beállításai'),
(2, 102, 'Mutasd az átfedést'),
(2, 103, 'Információ figyelmen kívül hagyása, ha régebbi mint'),
(2, 104, 'napos'),
(2, 105, 'Kiemelések'),
(2, 106, 'Nincs'),
(2, 107, 'Van csoportja'),
(2, 108, 'Van infromáció'),
(2, 109, 'Nukes szükséges'),
(2, 110, 'Foglalások'),
(2, 111, 'Erősítések'),
(2, 112, 'Fal szint alatt'),
(2, 114, 'Visszatérő csapatok több mint'),
(2, 115, 'ezer pop'),
(2, 116, 'Őrtorony szint felett'),
(2, 117, 'Védőcsapat'),
(2, 118, 'Kis erősítés az'),
(2, 119, 'és a nagy erősítés'),
(2, 120, 'Emeld ki a falvakat itt'),
(2, 121, 'klán'),
(2, 122, 'Send Recap'),
(2, 123, 'Akciók/Értesítések'),
(2, 124, '(Nincsenek visszafoglalások)'),
(2, 125, '{duration} ideje'),
(2, 126, 'Lista a nemrég elfoglalt baráti falvakról.'),
(2, 127, 'Csak azokat az visszafoglalások mutasd, ahol nemesek vannak a közelben.'),
(2, 128, 'Falu'),
(2, 129, 'Hűség'),
(2, 130, 'Meghódítva ekkor'),
(2, 131, 'Régi tulaj'),
(2, 132, 'Új tulaj'),
(2, 133, 'Snipes szükséges'),
(2, 134, '(Nincs szükség snipe-ra)'),
(2, 135, 'Lista a beérkező vonatokról, amelyekhez rendelkezel csapatokkal a snipe-oláshoz.'),
(2, 136, '# Nemesek'),
(2, 137, 'Időpont'),
(2, 139, 'Küldj erősítést'),
(2, 140, '(Nincs erősítés javasolva)'),
(2, 141, 'Túlél {numNukes} nukes'),
(2, 142, 'Lista azokról a falvakról, amelyeket erősíteni kell a beérkező támadások és az ott állomásozó jelenlegi védelem alapján.'),
(2, 143, 'Lehetséges nuke-k'),
(2, 144, 'Jelenlegi védelmi erősség'),
(2, 145, 'Nemes célpontok'),
(2, 146, '(Nincsenek javasolt célpontok)'),
(2, 147, '{duration} ideje'),
(2, 148, 'A lehetséges nemes célpontok listája a náluk állomásozó védelem és az aktuális hűség alapján.'),
(2, 149, 'Állomásozó védőcsapatok'),
(2, 150, 'Észlelt védők'),
(2, 151, 'Tulajdonos'),
(2, 152, 'Useless Stacks'),
(2, 153, '(Nincs felesleges erősítés)'),
(2, 154, 'A falvak listája, amelyeknek a támogatását haza kell küldeni, függetlenül attól, hogy hátországi falvakról vagy nem baráti falvakról van-e szó.'),
(2, 155, 'Klán'),
(2, 156, 'Populáció száma'),
(2, 157, 'Gyors támogatás'),
(2, 158, 'Játékos nem található!'),
(2, 159, 'Keress és küldj üzenetet a közeli védelemmel rendelkező játékosoknak.'),
(2, 160, 'Küldés ide'),
(2, 161, 'amely elérhet ennyi idő alatt'),
(2, 162, 'óra'),
(2, 163, 'Keresés'),
(2, 164, 'Eredmények'),
(2, 165, 'Erősítés kérése'),
(2, 166, 'Keress és küldj üzenetet a backline defense rendelkező játékosoknak.'),
(2, 167, 'Küldés ide'),
(2, 168, 'amely elérhet ennyi idő alatt'),
(2, 169, 'óra(optional)'),
(2, 170, 'Admin'),
(2, 171, 'Törlés'),
(2, 172, '{tribeName} többé nem lesz ellenségként kezelve.'),
(2, 173, 'Ellenséges klánok'),
(2, 174, 'Hiba történt az ellenséges klánok listázása közben...'),
(2, 175, 'Add meg a nevet vagy a klán rövidítését.'),
(2, 176, 'Nem létezik klán ilyen névvel vagy rövidítéssel.'),
(2, 177, 'Klán már ellenségként van regisztrálva.'),
(2, 178, 'Ellenséges klánok'),
(2, 179, 'Add meg a Vault-nak, hogy mely klánokat tekintse ' || chr(39) || chr(39) || 'ellenségnek' || chr(39) || chr(39) || ' annak meghatározásakor, hogy mely falvak számítanak háttérfalunak.'),
(2, 180, 'Ellenséges klán hozzáadása'),
(2, 181, 'Felhasználók kezelése'),
(2, 182, 'Kulcsok'),
(2, 183, 'Új kulcs létrehozása'),
(2, 184, 'Új Vault Script'),
(2, 185, 'Felhasználó név'),
(2, 186, 'Aktuális klán'),
(2, 187, 'Klán statisztikák'),
(2, 188, 'Folyamatban'),
(2, 189, 'Szerezd meg a klán hadseregének statisztikáit:'),
(2, 190, 'Tartalmazza a statisztikákat: 1/4, 1/2, és 3/4 nuke vonatkozóan'),
(2, 191, 'Letöltés'),
(2, 192, 'Log'),
(2, 193, 'Felhasználó Log'),
(2, 194, 'Admin'),
(2, 195, 'Esemény'),
(2, 196, 'Idő'),
(2, 197, 'Add meg a felhasználónevet vagy az azonosítót (ID).'),
(2, 198, 'Nincs klán'),
(2, 199, 'Adminná tétel'),
(2, 200, 'Admin visszavonása'),
(2, 201, 'Script igénylése'),
(2, 202, '{playerName} Vault-kulcsa eltávolításra kerül'),
(2, 203, '{playerName} többé nem rendelkezik adminisztrátori jogosultságokkal.'),
(2, 204, '{playerName} adminisztrátori jogosultságokat kap, és képes lesz: - Hozzáférni az összes elérhető csapatinformációhoz - Új felhasználókat hozzáadni - Felhasználók adminisztrátori jogosultságait megadni és visszavonni'),
(2, 205, 'Vault script: {playerName} számára'),
(2, 206, '1/4 Nukes'),
(2, 207, '1/2 Nukes'),
(2, 208, '3/4 Nukes'),
(2, 209, 'Összes full nuke'),
(2, 210, 'Összes nemes'),
(2, 211, 'Összes lehetséges nemes'),
(2, 212, 'Összes védő'),
(2, 213, 'Összes bejövő'),
(2, 214, 'Összes támadó'),
(2, 215, 'Feltöltés szükséges?'),
(2, 216, 'Igen'),
(2, 217, 'Játékos'),
(2, 218, 'Full Nukes'),
(2, 219, 'Nukes úton'),
(2, 220, 'Lehetséges nemesek'),
(2, 221, 'Birtokolt védő falvak'),
(2, 222, 'Védők otthon'),
(2, 223, 'Backline védő falvak a faluban'),
(2, 224, 'Védők úton'),
(2, 225, 'Védők más saját falvakban'),
(2, 226, 'Védők más játékosnál'),
(2, 227, 'Becsült támadó falvak'),
(2, 228, 'Becsült védő falvak'),
(2, 229, '# Bejövők'),
(2, 230, '# Támadások'),
(2, 231, 'Védők {tribeName} számára'),
(2, 234, 'Értesítések'),
(2, 241, 'Server idő'),
(2, 243, 'Üzenet'),
(2, 244, 'Hozzáadás'),
(2, 264, 'Nem kötelező'),
(2, 268, 'Mentés'),
(2, 275, 'Statisztika'),
(2, 282, 'Saját'),
(2, 283, 'Hiba történt a statisztikák betöltése közben'),
(2, 284, 'Utolsó 7 nap'),
(2, 285, 'Nukes'),
(2, 286, 'Fangs'),
(2, 287, 'Erősítés'),
(2, 288, 'Védelem'),
(2, 289, '# Védőcsapatok'),
(2, 290, 'Faluban'),
(2, 291, '(Backline) faluban'),
(2, 292, 'Úton'),
(2, 293, 'Támogatás'),
(2, 294, 'Magas pontszámok'),
(2, 295, 'Hiba történt a ranglista lekérése közben.'),
(2, 296, 'Ranglista'),
(2, 297, 'Támgotatás'),
(2, 298, 'Jogi nyilatkozatok és feltételek'),
(2, 299, 'Ez az eszköz nem az InnoGames támogatásával vagy fejlesztésével készült.'),
(2, 300, 'A Vault-hoz küldött összes adat és kérés biztonsági okokból naplózásra kerül. Ez kizárólag a következő információkra korlátozódik: Authetnikációs token, játékos ID, klán ID, kért végpont, és a tranzakció időpontja. A szkript által gyűjtött információk soha nem kerülnek megosztásra harmadik felekkel vagy jogosulatlan törzsekkel/játékosokkal.'),
(2, 301, 'Eszközök'),
(2, 302, 'Fake Script'),
(2, 303, 'Dinamikus Fake Scripts'),
(2, 304, 'Játékosok'),
(2, 305, 'Klánok'),
(2, 306, 'Kontinensek'),
(2, 307, 'Min koordináták'),
(2, 308, 'Max koordináták'),
(2, 310, 'Távolság középtől'),
(2, 311, 'mezők-től'),
(2, 312, 'Szerezd meg a koordinátákat'),
(2, 314, 'Találat: {numTimings} időzítés {numNukes} visszatérő nuke támadáshoz ' || chr(40) || '{numShown}' || chr(41)),
(2, 315, 'Find Backtimes'),
(2, 316, 'Folyamatban... (Ez eltarthat egy ideig)'),
(2, 318, 'Szerezd meg az összes elérhető backtime tervet az ellenséges nuke támadásokhoz a Vault-ban feltöltött csapatok felhasználásával.'),
(2, 319, 'Töltsd fel a csapataidat gyakran a legpontosabb időzítések érdekében!'),
(2, 320, 'Minimális visszatérő egység'),
(2, 321, 'Minimum támadás méret:'),
(2, 322, '% of a full nuke'),
(2, 323, 'Max utazási idő'),
(2, 324, 'Időzítések maximális száma:'),
(2, 325, 'Visszaidőzített nuke támadások elrejtése:'),
(2, 326, 'Hide stacked nukes:'),
(2, 327, 'Feltöltés'),
(2, 328, 'Feltölti az összes adatot az összes új jelentésből.'),
(2, 329, 'Feltölti az összes elérhető adatot a Bejövő csapatok oldalon. Ez magában foglalja a támadásokat és a támogatásokat.'),
(2, 330, 'Feltölti az összes adatot az összes jelenlegi parancsaidhoz.'),
(2, 331, 'Feltölti az összes adatot az összes egység számára.'),
(2, 332, 'Helyi Vault gyorsítótár (cache) törölve.'),
(2, 333, 'Várakozás'),
(2, 334, 'Váratlan hiba történt:'),
(2, 335, 'Feltöltés'),
(2, 336, 'Folyamat'),
(2, 340, 'Részletek'),
(2, 341, 'Kattints az \"Összes feltöltése\" gombra. Ha szükséges, külön-külön tölts fel más dolgokat a többi Feltöltés gomb használatával.'),
(2, 342, 'Jelentések'),
(2, 345, 'Bejövő csapatok'),
(2, 347, 'Parancsok'),
(2, 348, 'Összes feltöltése'),
(2, 349, 'Gyorsítótár (cache) kiürítése'),
(2, 356, 'Parancsoldalak gyűjtése...'),
(2, 357, 'Befejezve: Nincs új parancs feltöltéshez.'),
(2, 358, 'Korábban feltöltött parancsok ellenőrzése...'),
(2, 359, 'Parancsok feltöltése...'),
(2, 360, 'Befejezve: {numDone}/{numTotal} feltöltve, {numFailed} hibás.'),
(2, 361, 'Nem sikerült ellenőrizni a régi parancsokat, minden feltöltésre kerül...'),
(2, 362, 'Talált {numCommands} régi parancs, figyelmen kívül hagyva...'),
(2, 363, '{numDone}/{numTotal} kész, {numFailed} hibás'),
(2, 364, 'Bejövő oldalak gyüjtése...'),
(2, 365, '({numDone}/{numTotal} kész, {numFailed} hibás)'),
(2, 366, 'Bejövők feltöltése...'),
(2, 367, 'Befejezve: Uploaded {numIncomings} bejövő.'),
(2, 368, 'Jelentése oldalak gyüjtése...'),
(2, 369, 'Jelentés hivatkozások gyűjtése...'),
(2, 370, 'Jelentés oldalak gyűjtése... (oldal {numDone}/{numTotal})'),
(2, 371, 'Korábban feltöltöltött jelentések ellenőrzése...'),
(2, 372, 'Nem található Farmkezelő mappa, figyelmen kívül hagyás...'),
(2, 373, 'Farmkezelő'),
(2, 374, 'Farmkezelő jelentések szűrése...'),
(2, 375, 'Hiba történt a Farmkezelő mappa elérésekor, figyelmen kívül hagyás...'),
(2, 376, 'Találat: {numOld} korábban feltöltött jelentés, ezek kihagyása...'),
(2, 377, 'Hiba történt a meglévő jelentések ellenőrzésekor, folytatás...'),
(2, 378, 'Befejezve: {numDone}/{numTotal} feltöltve, {numFailed} hibás.'),
(2, 379, 'Befejezve: Nincs új jelentés, amit fel lehetne tölteni.'),
(2, 380, 'Feltöltés {numTotal} jelentés... ' || chr(40) || '{numDone} kész, {numFailed} hibás.' || chr(41)),
(2, 381, 'Falu csapatai oldal lekérése...'),
(2, 382, 'Akadémiával rendelkező falu keresése...'),
(2, 383, '(Nem található akadémiával rendelkező falu)'),
(2, 384, 'Lehetséges nemesek lekérése...'),
(2, 385, 'Támogatás lekérése...'),
(2, 386, 'Támogatott falvak és védő egységek gyűjtése...'),
(2, 387, 'Hiba történt az akadémiával rendelkező falu keresése közben...'),
(2, 388, 'Nemesek korlátja:{numNobles}'),
(2, 389, 'Elfoglalt falvak száma:{numVillages}'),
(2, 390, 'Hiba történt a lehetséges nemesek számának lekérése közben...'),
(2, 391, 'Csapatok feltöltése a Vault-ba...'),
(2, 392, 'Hiba történt a Vault-ba történő feltöltés során.'),
(2, 393, 'Befejezve: Csapatok feltöltve {numVillages} faluhoz.'),
(2, 394, 'Támogató egységek feltöltése a Vault-ba...'),
(2, 395, 'Kos'),
(2, 396, 'Kos, faltörő kos'),
(2, 397, 'Kataplult'),
(2, 398, 'Katapult, kata, katák'),
(2, 399, 'Lándzsás'),
(2, 400, 'lándzsás, lándzsa, talpas'),
(2, 401, 'Kardforgató'),
(2, 402, 'kardforgató, kardos, sw'),
(2, 403, 'Bárdos'),
(2, 404, 'bárdos'),
(2, 405, 'Íjász'),
(2, 406, 'íjász, íj'),
(2, 407, 'Kém'),
(2, 408, 'kém, kémek, sc'),
(2, 409, 'Könnyűlovas'),
(2, 410, 'könnyűlovas, könnyűló, light, lc'),
(2, 411, 'Lovas íjász'),
(2, 412, 'lovas íjász, mounted archer, marcher, ma'),
(2, 413, 'Nehézlovas'),
(2, 414, 'nehézlovas, nehézló, nló, heavy'),
(2, 415, 'Lovag'),
(2, 416, 'lovag, pally'),
(2, 417, 'Főhadiszállás'),
(2, 418, 'Barakk'),
(2, 419, 'Istálló'),
(2, 420, 'Műhely'),
(2, 421, 'Akadémia'),
(2, 422, 'Kovácsműhely'),
(2, 423, 'Gyülekezőhely'),
(2, 424, 'Szobor'),
(2, 425, 'Piac'),
(2, 426, 'Fatelep'),
(2, 427, 'Agyagbánya'),
(2, 428, 'Vasbánya'),
(2, 429, 'Tanya'),
(2, 430, 'Raktár'),
(2, 431, 'Rejtekhely'),
(2, 432, 'Fal'),
(2, 433, 'Őrtorony'),
(2, 434, 'Templom'),
(2, 435, '{oldLoyalty} -ról {newLoyalty} -ra'),
(2, 438, 'table'),
(2, 439, 'A Tribal Wars Captcha aktiválódott, kérlek, frissítsd az oldalt, és próbáld újra. Minden feltöltés onnan folytatódik, ahol abbamaradt.'),
(2, 440, 'A jelenlegi falu csoportod nem ' || chr(39) || chr(39) || 'Összes' || chr(39) || chr(39) || '. Kérlek, váltsd át az ' || chr(39) || chr(39) || 'Összes' || chr(39) || chr(39) || ' csoportra.'),
(2, 441, 'Szűrők vannak beállítva {dataType} adatra, kérlek, távolítsd el őket a feltöltés előtt.'),
(2, 448, 'jan., febr., márc., ápr., máj., jún., júl., aug., szept., okt., nov., dec.'),
(2, 449, 'ma ekkor: {time}'),
(2, 450, 'holnap ekkor: {time}'),
(2, 451, '{time}, érkezés ekkor: {date}'),
(2, 452, '{date} napon {time} órakor'),
(2, 453, '{hour}:{minute}:{second}:{millisecond}, ebben az időben: {day}.{month}.{year}'),
(2, 454, 'nap'),
(2, 455, 'hr'),
(2, 456, 'min'),
(2, 457, 'sec'),
(2, 458, 'napok'),
(2, 459, 'óra'),
(2, 460, 'mins'),
(2, 461, 'secs'),
(2, 462, '{numDone}/{numTotal} kész, {numFailed} hibás'),
(2, 463, 'Kulcs hozzáadva {playerName} számára.'),
(2, 464, '{playerName} adminisztrátori jogosultságait visszavonta.'),
(2, 465, 'Adminisztrátori jogosultságokat adott {playerName} számára.'),
(2, 466, '{playerName} kulcsa újra engedélyezve.'),
(2, 467, '{playerName} kulcsa letiltva.'),
(2, 468, 'A kulcs tulajdonosát {oldPlayer}-ról {newPlayer}-ra változtatta.'),
(2, 469, '{playerName} kulcsát csak olvasható módba állította'),
(2, 470, '{playerName} kulcsa már nem csak olvasható.'),
(2, 471, 'A {playerName} számára kijelölt szerver megváltozott.'),
(2, 472, '{playerName} adminisztrátori jogosultságát eltávolította.'),
(2, 473, '{adminName} adminisztrátori jogosultságokat adott {playerName} számára.'),
(2, 474, '{playerName} adminisztrátorát {oldAdmin}-ról {newAdmin}-ra változtatta.'),
(2, 475, '{playerName} frissítve (ismeretlen változás).'),
(2, 476, 'Töröl kulcs {playerName} számára.'),
(2, 477, 'Nem található játékos a megadott játékosazonosítóval.'),
(2, 478, 'Nem található játékos a megadott játékosazonosítóval.'),
(2, 479, 'Meg kell adni vagy a játékos azonosítóját, vagy a játékos nevét.'),
(2, 480, 'Nem kérhetsz kulcsot olyan játékos számára, aki nincs a klánodban.'),
(2, 481, 'Ez a felhasználó már rendelkezik kulccsal.'),
(2, 482, 'Érvénytelen Vault-kulcs.'),
(2, 483, 'Nincs olyan felhasználó, aki ezzel a Vault-kulccsal rendelkezne.'),
(2, 484, 'Nem törölheted a saját kulcsodat.'),
(2, 485, 'Nem törölhetsz egy olyan adminisztrátori felhasználót, akit nem te hoztál létre.'),
(2, 486, 'Nem módosíthatod a saját kulcsod adminisztrátori státuszát.'),
(2, 487, 'Nem módosíthatod egy olyan felhasználó adminisztrátori státuszát, akit nem te hoztál létre.'),
(2, 488, 'Nincs'),
(2, 489, 'Támadás'),
(2, 491, 'óra'),
(2, 493, 'Nemesek'),
(2, 494, 'Név'),
(2, 495, 'Beállítások'),
(2, 496, 'Nincs bejövő!'),
(2, 497, 'Hiba történt az adatok feltöltése közben.'),
(2, 498, 'nemes, nobleman, nobles'),
(2, 499, 'FN'),
(2, 501, 'Támogatásod innen'),
(2, 503, 'Nukes'),
(2, 504, 'Vault Tagging'),
(2, 505, 'Távolság a küldő és a cél falu között'),
(2, 506, 'Előnézet'),
(2, 507, 'Vault - innen származó parancsok'),
(2, 510, 'Értesítések'),
(2, 511, 'unit'),
(2, 512, 'url'),
(2, 513, 'Segítség'),
(2, 514, 'Fordítások'),
(2, 515, 'Nyelv:'),
(2, 516, 'Fordítás:'),
(2, 517, 'Beállítások Mentése'),
(2, 518, 'Fordítás szerkesztése'),
(2, 519, 'Új fordítás'),
(2, 520, 'Változtatások mentése'),
(2, 521, '{name} {author} által készítve.'),
(2, 522, 'Kulcs'),
(2, 523, 'Érték'),
(2, 524, 'Angol példa'),
(2, 525, 'A fordítás a/z {keyName} -hoz hiányzik: {parameters}'),
(2, 526, 'Megjegyzés: Ez játékbeli szöveg, pontosan meg kell egyeznie!'),
(2, 527, 'Változtatások mentve!'),
(2, 528, 'Fordítás törlése'),
(2, 529, 'Biztosan törölni akarod a fordításodat, \"\"\"\" {name}\"\"\"\"?'),
(2, 530, 'Nem törölheted a fordítást, ha az alapértelmezettként van használva!'),
(2, 531, 'Még nem mentetted el a fordításodat!'),
(2, 532, 'Sikeresen törölve a fordítás.'),
(2, 534, 'Már van egy fordításod ezzel a névvel \"\"\"\" {name}\"\"\"\"!'),
(2, 535, 'Mivel nem te birtoklod ezt a fordítást, egy másolatot fogsz szerkeszteni.'),
(2, 536, 'Nincs elérhető friss seregadat.'),
(2, 537, 'Nincs elérhető friss épületadat.'),
(2, 538, '{day}/{month}/{year}'),
(2, 539, 'Ellenség'),
(2, 540, 'A falat találat érte és {oldLevel} szintről {newLevel} szintre sérült'),
(2, 541, 'A(z) {buildingName} megrongálódott, és {oldLevel} szintről {newLevel} szintre sérült'),
(2, 543, 'Célállomás'),
(2, 544, 'Fangs legalább {numCats} katapulttal és legfeljebb {maxPop} egységgel'),
(2, 545, 'Fangs úton'),
(2, 546, 'Total Fangs'),
(2, 547, 'Beállítások'),
(2, 548, 'Nincs kihagyott jelentésmappa.'),
(2, 549, 'Kuka'),
(2, 550, 'Mappa kihagyása'),
(2, 551, 'Jelentés feltöltésének beállításai'),
(2, 552, 'Kihagyott jelentésmappák'),
(2, 553, 'Az összes jelentésmappa ki van zárva a beállításaid szerint!'),
(2, 554, '{month} {day}, {year} {hour}:{minute}:{second}:{millis}'),
(2, 555, 'Pontok'),
(2, 556, 'Minimum falu pontjai:'),
(2, 557, '{hour}:{minute}:{second}:{millis} {hour}:{minute}:{second} {hour}:{minute}'),
(2, 558, '{monthName} {day}, {year} {day}/{month}/{year} {day}.{month}.'),
(2, 559, '{monthName} {day}, {hour}:{minute} {monthName} {day},{year} {hour}:{minute} {hour}:{minute}:{second}:{millisecond} on {day}:{month}:{year}'),
(2, 560, 'Beérkező nukes'),
(2, 561, 'Feltöltés engedélyezve (kattints a letiltáshoz)'),
(2, 562, 'Feltöltés letiltva (kattints az engedélyezéshez)'),
(2, 563, 'Biztos le szeretnéd tiltani a feltöltéseket ?'),
(2, 564, 'Feltöltés engedélyezése'),
(2, 565, 'Elolvastad és elfogadod a feltételeket ?'),
(2, 566, 'A feltöltés jelenleg nincs engedélyezve! Előbb engedélyezd a Feltöltés engedélyezése gombbal.'),
(2, 567, 'Elfogadom'),
(2, 568, 'A(z) Vault semmilyen személyes infromációt nem gyüjt az eszközdről, csupán a klánháborúban (röviden TW) elérhető adatokat nyeri ki. Ezen adatok a következőek: Játékos neved (játékos felhasználód ID-je), a klánod neve (klánod ID-je), Térkép és csapat adatok. A(z) Vault által összegyüjtött adatok a SAJÁT eszközöd lokális tárolójában kerülnek eltárolásra. A TW korlátozza a személyes online adataid küldését harmadik fél számára, ezért a Vault a SAJÁT lokális tárolódat használja az adatok feltötéséhez! A beleegyezéseddel elfogadod, hogy a játékbeli online adataidat a Vault elküdje a szerverre!')
ON CONFLICT (translation_id, key) DO UPDATE SET value = EXCLUDED.value;
"

echo "All Hungarian translations imported successfully!"
echo "Total translations: $(sudo -u postgres psql -d vault -t -c 'SELECT COUNT(*) FROM feature.translation WHERE translation_id = 2;')"
