sudo -u postgres psql -d vault << 'EOF'
INSERT INTO feature.translation (translation_id, key, value) VALUES
(2, 418, 'Barakk'),
(2, 419, 'Istálló'),
(2, 420, 'Műhely'),
(2, 421, 'Akadémia'),
(2, 422, 'Kovácsműhely'),
(2, 423, 'Gyülekezőhely'),
(2, 424, 'Szobor'),
(2, 425, 'Piac'),
(2, 426, 'Fatelep'),
(2, 427, 'Agyagbánya'),
(2, 428, 'Vasbánya'),
(2, 429, 'Tanya'),
(2, 430, 'Raktár'),
(2, 431, 'Rejtekhely'),
(2, 432, 'Fal'),
(2, 433, 'Őrtorony'),
(2, 434, 'Templom'),
(2, 435, '{oldLoyalty} -ról {newLoyalty} -ra'),
(2, 438, 'table'),
(2, 439, 'A Tribal Wars Captcha aktiválódott, kérlek, frissítsd az oldalt, és próbáld újra. Minden feltöltés onnan folytatódik, ahol abbamaradt.'),
(2, 440, 'A jelenlegi falu csoportod nem ''Összes''. Kérlek, váltsd át az ''Összes'' csoportra.'),
(2, 441, 'Szűrők vannak beállítva {dataType} adatra, kérlek, távolítsd el őket a feltöltés előtt.'),
(2, 462, '{numDone}/{numTotal} kész, {numFailed} hibás'),
(2, 463, 'Kulcs hozzáadva {playerName} számára.'),
(2, 464, '{playerName} adminisztrátori jogosultságait visszavonta.'),
(2, 465, 'Adminisztrátori jogosultságokat adott {playerName} számára.'),
(2, 466, '{playerName} kulcsa újra engedélyezve.'),
(2, 467, '{playerName} kulcsa letiltva.'),
(2, 468, 'A kulcs tulajdonosát {oldPlayer}-ról {newPlayer}-ra változtatta.'),
(2, 469, '{playerName} kulcsát csak olvasható módba állította'),
(2, 470, '{playerName} kulcsa már nem csak olvasható.'),
(2, 471, 'A {playerName} számára kijelölt szerver megváltozott.'),
(2, 472, '{playerName} adminisztrátori jogosultságát eltávolította.'),
(2, 473, '{adminName} adminisztrátori jogosultságokat adott {playerName} számára.'),
(2, 474, '{playerName} adminisztrátorát {oldAdmin}-ról {newAdmin}-ra változtatta.'),
(2, 475, '{playerName} frissítve (ismeretlen változás).'),
(2, 476, 'Töröl kulcs {playerName} számára.'),
(2, 477, 'Nem található játékos a megadott játékosazonosítóval.'),
(2, 478, 'Nem található játékos a megadott játékosazonosítóval.'),
(2, 479, 'Meg kell adni vagy a játékos azonosítóját, vagy a játékos nevét.')
ON CONFLICT (translation_id, key) DO UPDATE SET value = EXCLUDED.value;
EOF
