sudo -u postgres psql -d vault << 'EOF'
INSERT INTO feature.translation (translation_id, key, value) VALUES
(2, 480, 'Nem kérhetsz kulcsot olyan játékos számára, aki nincs a klánodban.'),
(2, 481, 'Ez a felhasználó már rendelkezik kulccsal.'),
(2, 482, 'Érvénytelen Vault-kulcs.'),
(2, 483, 'Nincs olyan felhasználó, aki ezzel a Vault-kulccsal rendelkezne.'),
(2, 484, 'Nem törölheted a saját kulcsodat.'),
(2, 485, 'Nem törölhetsz egy olyan adminisztrátori felhasználót, akit nem te hoztál létre.'),
(2, 486, 'Nem módosíthatod a saját kulcsod adminisztrátori státuszát.'),
(2, 487, 'Nem módosíthatod egy olyan felhasználó adminisztrátori státuszát, akit nem te hoztál létre.'),
(2, 488, 'Nincs'),
(2, 489, 'Támadás'),
(2, 491, 'óra'),
(2, 493, 'Nemesek'),
(2, 494, 'Név'),
(2, 495, 'Beállítások'),
(2, 496, 'Nincs bejövő!'),
(2, 497, 'Hiba történt az adatok feltöltése közben.'),
(2, 498, 'nemes, nobleman, nobles'),
(2, 499, 'FN'),
(2, 501, 'Támogatásod innen'),
(2, 503, 'Nukes'),
(2, 504, 'Vault Tagging'),
(2, 505, 'Távolság a küldő és a cél falu között'),
(2, 506, 'Előnézet'),
(2, 507, 'Vault - innen származó parancsok'),
(2, 510, 'Értesítések'),
(2, 511, 'unit'),
(2, 512, 'url'),
(2, 513, 'Segítség'),
(2, 514, 'Fordítások'),
(2, 515, 'Nyelv:'),
(2, 516, 'Fordítás:'),
(2, 517, 'Beállítások Mentése'),
(2, 518, 'Fordítás szerkesztése'),
(2, 519, 'Új fordítás'),
(2, 520, 'Változtatások mentése'),
(2, 521, '{name} {author} által készítve.'),
(2, 522, 'Kulcs'),
(2, 523, 'Érték'),
(2, 524, 'Angol példa'),
(2, 525, 'A fordítás a/z {keyName} -hoz hiányzik: {parameters}'),
(2, 526, 'Megjegyzés: Ez játékbeli szöveg, pontosan meg kell egyeznie!'),
(2, 527, 'Változtatások mentve!')
ON CONFLICT (translation_id, key) DO UPDATE SET value = EXCLUDED.value;
EOF