sudo -u postgres psql -d vault << 'EOF'
INSERT INTO feature.translation (translation_id, key, value) VALUES
(2, 528, 'Fordítás törlése'),
(2, 529, 'Biztosan törölni akarod a fordításodat, "{name}"?'),
(2, 530, 'Nem törölheted a fordítást, ha az alapértelmezettként van használva!'),
(2, 531, 'Még nem mentetted el a fordításodat!'),
(2, 532, 'Sikeresen törölve a fordítás.'),
(2, 534, 'Már van egy fordításod ezzel a névvel "{name}"!'),
(2, 535, 'Mivel nem te birtoklod ezt a fordítást, egy másolatot fogsz szerkeszteni.'),
(2, 536, 'Nincs elérhető friss seregadat.'),
(2, 537, 'Nincs elérhető friss épületadat.'),
(2, 538, '{day}/{month}/{year}'),
(2, 539, 'Ellenség'),
(2, 540, 'A falat találat érte és {oldLevel} szintről {newLevel} szintre sérült'),
(2, 541, 'A(z) {buildingName} megrongálódott, és {oldLevel} szintről {newLevel} szintre sérült'),
(2, 543, 'Célállomás'),
(2, 544, 'Fangs legalább {numCats} katapulttal és legfeljebb {maxPop} egységgel'),
(2, 545, 'Fangs úton'),
(2, 546, 'Total Fangs'),
(2, 547, 'Beállítások'),
(2, 548, 'Nincs kihagyott jelentésmappa.'),
(2, 549, 'Kuka'),
(2, 550, 'Mappa kihagyása'),
(2, 551, 'Jelentés feltöltésének beállításai'),
(2, 552, 'Kihagyott jelentésmappák'),
(2, 553, 'Az összes jelentésmappa ki van zárva a beállításaid szerint!'),
(2, 555, 'Pontok'),
(2, 556, 'Minimum falu pontjai:'),
(2, 560, 'Beérkező nukes'),
(2, 561, 'Feltöltés engedélyezve (kattints a letiltáshoz)'),
(2, 562, 'Feltöltés letiltva (kattints az engedélyezéshez)'),
(2, 563, 'Biztos le szeretnéd tiltani a feltöltéseket ?'),
(2, 564, 'Feltöltés engedélyezése'),
(2, 565, 'Elolvastad és elfogadod a feltételeket ?'),
(2, 566, 'A feltöltés jelenleg nincs engedélyezve! Előbb engedélyezd a Feltöltés engedélyezése gombbal.'),
(2, 567, 'Elfogadom')
ON CONFLICT (translation_id, key) DO UPDATE SET value = EXCLUDED.value;
EOF
