sudo -u postgres psql -d vault << 'EOF'
INSERT INTO feature.translation (translation_id, key, value) VALUES
(2, 41, '# a faluban ismert katapultok száma'),
(2, 42, '# Összes parancs száma a faluból'),
(2, 43, 'Támadó játékos neve'),
(2, 44, 'Támadó játékos falva'),
(2, 45, 'Védekező neve'),
(2, 46, 'Védekező játékos falva'),
(2, 47, 'Származási hely koordinátái'),
(2, 48, 'Célállomás'),
(2, 49, 'A falu típusa: támadó, védekező vagy ismeretlen'),
(2, 50, 'Az általad hozzáadott egyéni címkék a parancshoz, amelyeket érintetlenül kell hagyni; ezek idézőjelek között jelennek meg, például „Kitért".'),
(2, 51, 'Tag format:'),
(2, 52, 'Reset'),
(2, 53, 'Csak a címkézetlen bejövőket jelöld meg'),
(2, 54, 'Címkézés „Fake"-ként, ha kevesebb mint'),
(2, 55, 'ezer támadó népesség'),
(2, 56, 'Adatok nélküli bejövők támadások figyelmen kívül hagyása'),
(2, 57, 'Cimkézd összeset'),
(2, 58, 'Kiválasztott cimkézése'),
(2, 59, 'Visszaállítás a korábbi címkékre'),
(2, 60, 'Mégse'),
(2, 61, 'A címkézés eltarthat egy ideig!'),
(2, 62, 'Nem szám!'),
(2, 63, 'FIGYELMEZTETÉS – A fake-ek felismerése nem 100%-osan pontos, de bekapcsoltad a „címkézés fake-ként" opciót!'),
(2, 64, 'Nem választottál ki bejövő támadást!'),
(2, 65, 'Nincsenek bejövők, vagy minden címke naprakész.'),
(2, 66, 'Cimkézés megszakítva'),
(2, 67, '{numDone}/{numTotal} cimkézve ({numFailed} nem skerült)'),
(2, 68, 'Cimkézés:'),
(2, 69, 'Befejezve:'),
(2, 70, 'Megszakítva:'),
(2, 71, 'Ismeretlen'),
(2, 72, 'Fakes'),
(2, 73, 'Fake'),
(2, 74, 'Nuke?'),
(2, 75, 'Vault használva'),
(2, 76, 'Bármelyik'),
(2, 77, 'Nem'),
(2, 78, 'Már régóta nem töltöttél fel adatot, ezért a térképes scriptet nem tudod használni, amíg ezt meg nem teszed. Kattints fent az oldal tetején található „Megjelenítés" hivatkozásra a feltöltés megkezdéséhez. (Ezután frissítsd az oldalt.)'),
(2, 79, '# Fakes'),
(2, 80, '# Nukes')
ON CONFLICT (translation_id, key) DO UPDATE SET value = EXCLUDED.value;
EOF
