sudo -u postgres psql -d vault << 'EOF'
INSERT INTO feature.translation (translation_id, key, value) VALUES
(2, 121, 'klán'),
(2, 122, 'Send Recap'),
(2, 123, 'Akciók/Értesítések'),
(2, 124, '(Nincsenek visszafoglalások)'),
(2, 125, '{duration} ideje'),
(2, 126, 'Lista a nemrég elfoglalt baráti falvakról.'),
(2, 127, 'Csak azokat az visszafoglalások mutasd, ahol nemesek vannak a közelben.'),
(2, 128, 'Falu'),
(2, 129, 'Hűség'),
(2, 130, 'Meghódítva ekkor'),
(2, 131, 'Régi tulaj'),
(2, 132, 'Új tulaj'),
(2, 133, 'Snipes szükséges'),
(2, 134, '(Nincs szükség snipe-ra)'),
(2, 135, 'Lista a beérkező vonatokról, amelyekhez rendelkezel csapatokkal a snipe-oláshoz.'),
(2, 136, '# Nemesek'),
(2, 137, 'Időpont'),
(2, 139, 'Küldj erősítést'),
(2, 140, '(Nincs erősítés javasolva)'),
(2, 141, 'Túlél {numNukes} nukes'),
(2, 142, 'Lista azokról a falvakról, amelyeket erősíteni kell a beérkező támadások és az ott állomásozó jelenlegi védelem alapján.'),
(2, 143, 'Lehetséges nuke-k'),
(2, 144, 'Jelenlegi védelmi erősség'),
(2, 145, 'Nemes célpontok'),
(2, 146, '(Nincsenek javasolt célpontok)'),
(2, 147, '{duration} ideje'),
(2, 148, 'A lehetséges nemes célpontok listája a náluk állomásozó védelem és az aktuális hűség alapján.'),
(2, 149, 'Állomásozó védőcsapatok'),
(2, 150, 'Észlelt védők'),
(2, 151, 'Tulajdonos'),
(2, 152, 'Useless Stacks'),
(2, 153, '(Nincs felesleges erősítés)'),
(2, 154, 'A falvak listája, amelyeknek a támogatását haza kell küldeni, függetlenül attól, hogy hátországi falvakról vagy nem baráti falvakról van-e szó.'),
(2, 155, 'Klán'),
(2, 156, 'Populáció száma'),
(2, 157, 'Gyors támogatás'),
(2, 158, 'Játékos nem található!'),
(2, 159, 'Keress és küldj üzenetet a közeli védelemmel rendelkező játékosoknak.'),
(2, 160, 'Küldés ide')
ON CONFLICT (translation_id, key) DO UPDATE SET value = EXCLUDED.value;
EOF
