sudo -u postgres psql -d vault << 'EOF'
INSERT INTO feature.translation (translation_id, key, value) VALUES
(2, 161, 'amely elérhet ennyi idő alatt'),
(2, 162, 'óra'),
(2, 163, 'Keresés'),
(2, 164, 'Eredmények'),
(2, 165, 'Erősítés kérése'),
(2, 166, 'Keress és küldj üzenetet a backline defense rendelkező játékosoknak.'),
(2, 167, 'Küldés ide'),
(2, 168, 'amely elérhet ennyi idő alatt'),
(2, 169, 'óra(optional)'),
(2, 170, 'Admin'),
(2, 171, 'Törlés'),
(2, 172, '{tribeName} többé nem lesz ellenségként kezelve.'),
(2, 173, 'Ellenséges klánok'),
(2, 174, 'Hiba történt az ellenséges klánok listázása közben...'),
(2, 175, 'Add meg a nevet vagy a klán rövidítését.'),
(2, 176, 'Nem létezik klán ilyen névvel vagy rövidítéssel.'),
(2, 177, 'Klán már ellenségként van regisztrálva.'),
(2, 178, 'Ellenséges klánok'),
(2, 179, 'Add meg a Vault-nak, hogy mely klánokat tekintse ''ellenségnek'' annak meghatározásakor, hogy mely falvak számítanak háttérfalunak.'),
(2, 180, 'Ellenséges klán hozzáadása'),
(2, 181, 'Felhasználók kezelése'),
(2, 182, 'Kulcsok'),
(2, 183, 'Új kulcs létrehozása'),
(2, 184, 'Új Vault Script'),
(2, 185, 'Felhasználó név'),
(2, 186, 'Aktuális klán'),
(2, 187, 'Klán statisztikák'),
(2, 188, 'Folyamatban'),
(2, 189, 'Szerezd meg a klán hadseregének statisztikáit:'),
(2, 190, 'Tartalmazza a statisztikákat: 1/4, 1/2, és 3/4 nuke vonatkozóan'),
(2, 191, 'Letöltés'),
(2, 192, 'Log'),
(2, 193, 'Felhasználó Log'),
(2, 194, 'Admin'),
(2, 195, 'Esemény'),
(2, 196, 'Idő'),
(2, 197, 'Add meg a felhasználónevet vagy az azonosítót (ID).'),
(2, 198, 'Nincs klán'),
(2, 199, 'Adminná tétel'),
(2, 200, 'Admin visszavonása')
ON CONFLICT (translation_id, key) DO UPDATE SET value = EXCLUDED.value;
EOF