sudo -u postgres psql -d vault << 'EOF'
INSERT INTO feature.translation (translation_id, key, value) VALUES
(2, 325, 'Visszaidőzített nuke támadások elrejtése:'),
(2, 326, 'Hide stacked nukes:'),
(2, 327, 'Feltöltés'),
(2, 328, 'Feltölti az összes adatot az összes új jelentésből.'),
(2, 329, 'Feltölti az összes elérhető adatot a Bejövő csapatok oldalon. Ez magában foglalja a támadásokat és a támogatásokat.'),
(2, 330, 'Feltölti az összes adatot az összes jelenlegi parancsaidhoz.'),
(2, 331, 'Feltölti az összes adatot az összes egység számára.'),
(2, 332, 'Helyi Vault gyorsítótár (cache) törölve.'),
(2, 333, 'Várakozás'),
(2, 334, 'Váratlan hiba történt:'),
(2, 335, 'Feltöltés'),
(2, 336, 'Folyamat'),
(2, 340, 'Részletek'),
(2, 341, 'Kattints az ""Összes feltöltése"" gombra. Ha szükséges, külön-külön tölts fel más dolgokat a többi Feltöltés gomb használatával.'),
(2, 342, 'Jelentések'),
(2, 345, 'Bejövő csapatok'),
(2, 347, 'Parancsok'),
(2, 348, 'Összes feltöltése'),
(2, 349, 'Gyorsítótár (cache) kiürítése'),
(2, 356, 'Parancsoldalak gyűjtése...'),
(2, 357, 'Befejezve: Nincs új parancs feltöltéshez.'),
(2, 358, 'Korábban feltöltött parancsok ellenőrzése...'),
(2, 359, 'Parancsok feltöltése...'),
(2, 360, 'Befejezve: {numDone}/{numTotal} feltöltve, {numFailed} hibás.'),
(2, 361, 'Nem sikerült ellenőrizni a régi parancsokat, minden feltöltésre kerül...'),
(2, 362, 'Talált {numCommands} régi parancs, figyelmen kívül hagyva...'),
(2, 363, '{numDone}/{numTotal} kész, {numFailed} hibás'),
(2, 364, 'Bejövő oldalak gyüjtése...'),
(2, 365, '({numDone}/{numTotal} kész, {numFailed} hibás)'),
(2, 366, 'Bejövők feltöltése...'),
(2, 367, 'Befejezve: Uploaded {numIncomings} bejövő.'),
(2, 368, 'Jelentése oldalak gyüjtése...'),
(2, 369, 'Jelentés hivatkozások gyűjtése...'),
(2, 370, 'Jelentés oldalak gyűjtése... (oldal {numDone}/{numTotal})'),
(2, 371, 'Korábban feltöltöltött jelentések ellenőrzése...'),
(2, 372, 'Nem található Farmkezelő mappa, figyelmen kívül hagyás...'),
(2, 373, 'Farmkezelő'),
(2, 374, 'Farmkezelő jelentések szűrése...'),
(2, 375, 'Hiba történt a Farmkezelő mappa elérésekor, figyelmen kívül hagyás...'),
(2, 376, 'Találat: {numOld} korábban feltöltött jelentés, ezek kihagyása...'),
(2, 377, 'Hiba történt a meglévő jelentések ellenőrzésekor, folytatás...')
ON CONFLICT (translation_id, key) DO UPDATE SET value = EXCLUDED.value;
EOF
