sudo -u postgres psql -d vault << 'EOF'
INSERT INTO feature.translation (translation_id, key, value) VALUES
(2, 378, 'Befejezve: {numDone}/{numTotal} feltöltve, {numFailed} hibás.'),
(2, 379, 'Befejezve: Nincs új jelentés, amit fel lehetne tölteni.'),
(2, 380, 'Feltöltés {numTotal} jelentés... ({numDone} kész, {numFailed} hibás.)'),
(2, 381, 'Falu csapatai oldal lekérése...'),
(2, 382, 'Akadémiával rendelkező falu keresése...'),
(2, 383, '(Nem található akadémiával rendelkező falu)'),
(2, 384, 'Lehetséges nemesek lekérése...'),
(2, 385, 'Támogatás lekérése...'),
(2, 386, 'Támogatott falvak és védő egységek gyűjtése...'),
(2, 387, 'Hiba történt az akadémiával rendelkező falu keresése közben...'),
(2, 388, 'Nemesek korlátja:{numNobles}'),
(2, 389, 'Elfoglalt falvak száma:{numVillages}'),
(2, 390, 'Hiba történt a lehetséges nemesek számának lekérése közben...'),
(2, 391, 'Csapatok feltöltése a Vault-ba...'),
(2, 392, 'Hiba történt a Vault-ba történő feltöltés során.'),
(2, 393, 'Befejezve: Csapatok feltöltve {numVillages} faluhoz.'),
(2, 394, 'Támogató egységek feltöltése a Vault-ba...'),
(2, 395, 'Kos'),
(2, 396, 'Kos, faltörő kos'),
(2, 397, 'Kataplult'),
(2, 398, 'Katapult, kata, katák'),
(2, 399, 'Lándzsás'),
(2, 400, 'lándzsás, lándzsa, talpas'),
(2, 401, 'Kardforgató'),
(2, 402, 'kardforgató, kardos, sw'),
(2, 403, 'Bárdos'),
(2, 404, 'bárdos'),
(2, 405, 'Íjász'),
(2, 406, 'íjász, íj'),
(2, 407, 'Kém'),
(2, 408, 'kém, kémek, sc'),
(2, 409, 'Könnyűlovas'),
(2, 410, 'könnyűlovas, könnyűló, light, lc'),
(2, 411, 'Lovas íjász'),
(2, 412, 'lovas íjász, mounted archer, marcher, ma'),
(2, 413, 'Nehézlovas'),
(2, 414, 'nehézlovas, nehézló, nló, heavy'),
(2, 415, 'Lovag'),
(2, 416, 'lovag, pally'),
(2, 417, 'Főhadiszállás')
ON CONFLICT (translation_id, key) DO UPDATE SET value = EXCLUDED.value;
EOF
